# Initially generated by GitHub Copilot.
"""Refresh UXLC-utils-sparse from the sibling UXLC-utils repo.

Run from repo root:
    .venv\\Scripts\\python.exe main_update_vendored_files.py

This script:
    1. Copies the designated sparse subset from ../UXLC-utils into UXLC-utils-sparse.
  2. Removes the legacy UXLC-utils-sparse/in/UXLC directory if present.
  3. Writes UXLC-utils-sparse/provenance.md with source git metadata and copied paths.
"""

import datetime
import shutil
import subprocess
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent
_SOURCE_REPO = _REPO.parent / "UXLC-utils"
_SPARSE_ROOT = _REPO / "UXLC-utils-sparse"

_LOCAL_ONLY_PATHS = {
    Path("provenance.md"),
}

_LEGACY_DEST_DIRS = [
    Path("in/UXLC"),
]


def _get_source_git_info() -> tuple[str, str | None]:
    """Return (commit_hash, tag_or_None) for UXLC-utils HEAD."""
    commit = subprocess.run(
        ["git", "-C", str(_SOURCE_REPO), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()

    tag_result = subprocess.run(
        ["git", "-C", str(_SOURCE_REPO), "describe", "--tags", "--exact-match", "HEAD"],
        capture_output=True,
        text=True,
    )
    tag = tag_result.stdout.strip() if tag_result.returncode == 0 else None
    return commit, tag


def _iter_local_files() -> list[Path]:
    """Return vendored local files under the sparse root, excluding local-only files."""
    rel_paths: list[Path] = []
    for local_path in sorted(_SPARSE_ROOT.rglob("*")):
        if not local_path.is_file():
            continue
        if "__pycache__" in local_path.parts:
            continue
        rel_path = local_path.relative_to(_SPARSE_ROOT)
        if rel_path in _LOCAL_ONLY_PATHS:
            continue
        rel_paths.append(rel_path)
    return rel_paths


def _sync_by_intersection() -> list[str]:
    """Copy existing local vendored files from the source repo."""
    synced_paths: list[str] = []
    for rel_path in _iter_local_files():
        src_file = _SOURCE_REPO / rel_path
        dest_file = _SPARSE_ROOT / rel_path
        if not src_file.is_file():
            raise FileNotFoundError(
                f"{rel_path.as_posix()} exists locally but not in UXLC-utils"
            )
        shutil.copy2(src_file, dest_file)
        synced_paths.append(rel_path.as_posix())
    return synced_paths


def _remove_legacy_paths() -> list[str]:
    removed: list[str] = []
    for rel_path in _LEGACY_DEST_DIRS:
        dest_path = _SPARSE_ROOT / rel_path
        if not dest_path.exists():
            continue
        if dest_path.is_dir():
            shutil.rmtree(dest_path)
        else:
            dest_path.unlink()
        removed.append(rel_path.as_posix())
    return removed


def _write_provenance(
    synced_paths: list[str],
    removed_paths: list[str],
    commit: str,
    tag: str | None,
    date_str: str,
) -> None:
    lines = [
        "<!-- Initially generated by GitHub Copilot. -->",
        "# Provenance of UXLC-utils-sparse",
        "",
        "These files were copied from the sibling UXLC-utils repo at:",
        "",
        "  GitRepos-relative path: UXLC-utils",
        "",
        "Vendored paths synced:",
    ]
    for rel_path in sorted(synced_paths):
        lines.append(f"  {rel_path}")
    if removed_paths:
        lines.append("")
        lines.append("Legacy paths removed:")
        for rel_path in sorted(removed_paths):
            lines.append(f"  {rel_path}")
    lines.append("")
    lines.append(f"Git commit: {commit}")
    if tag is not None:
        lines.append(f"Git tag:    {tag}")
    lines.append("")
    lines.append(f"Date copied: {date_str}")
    lines.append("")

    provenance_path = _SPARSE_ROOT / "provenance.md"
    provenance_path.write_text("\n".join(lines), encoding="utf-8")


def _reconfigure_stream_encoding(stream: object) -> None:
    reconfigure = getattr(stream, "reconfigure", None)
    if callable(reconfigure):
        reconfigure(encoding="utf-8")


def main() -> None:
    _reconfigure_stream_encoding(sys.stdout)
    _reconfigure_stream_encoding(sys.stderr)

    if not _SOURCE_REPO.is_dir():
        raise FileNotFoundError(
            f"UXLC-utils repo not found at {_SOURCE_REPO}. "
            "Expected as a sibling of this repo."
        )
    if not _SPARSE_ROOT.is_dir():
        raise FileNotFoundError(f"Sparse vendored subtree not found at {_SPARSE_ROOT}")

    commit, tag = _get_source_git_info()
    date_str = datetime.date.today().isoformat()

    synced_paths = _sync_by_intersection()
    removed_paths = _remove_legacy_paths()

    _write_provenance(synced_paths, removed_paths, commit, tag, date_str)

    print(f"Synced {len(synced_paths)} files")
    if removed_paths:
        print(f"Removed {len(removed_paths)} legacy paths")
    print(f"UXLC-utils commit: {commit}")
    if tag:
        print(f"UXLC-utils tag:    {tag}")


if __name__ == "__main__":
    main()