# Initially generated by GitHub Copilot.
"""Refresh UXLC-utils-sparse from the sibling UXLC-utils repo.

Run from repo root:
    .venv\\Scripts\\python.exe main_update_vendored_files.py

This script:
    1. Copies the designated sparse subset from ../UXLC-utils into UXLC-utils-sparse.
  2. Removes the legacy UXLC-utils-sparse/in/UXLC directory if present.
  3. Writes UXLC-utils-sparse/provenance.md with source git metadata and copied paths.
"""

import datetime
import shutil
import sys
from pathlib import Path

import vendoring_sync

_REPO = Path(__file__).resolve().parent
_SOURCE_REPO = _REPO.parent / "UXLC-utils"
_SPARSE_ROOT = _REPO / "UXLC-utils-sparse"

_LOCAL_ONLY_PATHS = {
    Path("provenance.md"),
}

_LEGACY_DEST_DIRS = [
    Path("in/UXLC"),
]


def _sync_by_intersection() -> list[str]:
    """Copy existing local vendored files from the source repo."""
    return vendoring_sync.copy_by_intersection(
        _SOURCE_REPO,
        _SPARSE_ROOT,
        include_suffixes=None,
        strict=True,
        recursive=True,
        exclude_rel_paths=[rel_path.as_posix() for rel_path in _LOCAL_ONLY_PATHS],
    )


def _remove_legacy_paths() -> list[str]:
    removed: list[str] = []
    for rel_path in _LEGACY_DEST_DIRS:
        dest_path = _SPARSE_ROOT / rel_path
        if not dest_path.exists():
            continue
        if dest_path.is_dir():
            shutil.rmtree(dest_path)
        else:
            dest_path.unlink()
        removed.append(rel_path.as_posix())
    return removed


def _reconfigure_stream_encoding(stream: object) -> None:
    reconfigure = getattr(stream, "reconfigure", None)
    if callable(reconfigure):
        reconfigure(encoding="utf-8")


def main() -> None:
    _reconfigure_stream_encoding(sys.stdout)
    _reconfigure_stream_encoding(sys.stderr)

    if not _SOURCE_REPO.is_dir():
        raise FileNotFoundError(
            f"UXLC-utils repo not found at {_SOURCE_REPO}. "
            "Expected as a sibling of this repo."
        )
    if not _SPARSE_ROOT.is_dir():
        raise FileNotFoundError(f"Sparse vendored subtree not found at {_SPARSE_ROOT}")

    commit, tag = vendoring_sync.get_git_info(_SOURCE_REPO)
    date_str = datetime.date.today().isoformat()

    synced_paths = _sync_by_intersection()
    removed_paths = _remove_legacy_paths()

    vendoring_sync.write_provenance(
        _SPARSE_ROOT,
        source_rel="UXLC-utils",
        copied_files=synced_paths,
        commit=commit,
        tag=tag,
        date_str=date_str,
        title="Provenance of UXLC-utils-sparse",
        removed_paths=removed_paths,
    )

    print(f"Synced {len(synced_paths)} files")
    if removed_paths:
        print(f"Removed {len(removed_paths)} legacy paths")
    print(f"UXLC-utils commit: {commit}")
    if tag:
        print(f"UXLC-utils tag:    {tag}")


if __name__ == "__main__":
    main()
